 *code ideas
 CALL METHOD LCL_STD_BADI->/STTPEC/IF_BADI_MD_SERTYPE~DETERMINE_SERTYPE
 
*   Get atinn for 'STTP_BLOCK_INTEGRATION'
    SELECT SINGLE atinn INTO l_char_atinn
      FROM cabn
      WHERE atnam = 'STTP_BLOCK_INTEGRATION'.
	  
   CALL FUNCTION 'CLFM_GET_AUSP_FROM_BUFFER'
   CALL FUNCTION 'CLFM_SELECT_AUSP'
   
   READ TABLE lt_ausp_buffer 